name: Deploy Infrastructure

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install AWS CDK
        run: npm install -g aws-cdk
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Install dependencies
        run: |
          cd infra
          npm install
          
      - name: Build
        run: |
          cd infra
          npm run build
          
      - name: Deploy
        run: |
          cd infra
          npx cdk deploy --require-approval never 